title:            HyperREST
description:      Don't stress about REST! Just REST!
url:              http://hyperrest.github.io
baseurl:
signoff:          Andrei
disqus_shortname: andreineculauhyperrest
google_analytics: UA-38765969-1

links:
  - name: About
    url: /about.html
  - name: API icons
    url: http://hyperrest.github.io/api-icons/
  - name: hyperrest/client
    url: http://github.com/hyperrest/client
  - name: hyperrest/...
    url: http://github.com/hyperrest
  - name: for-GET/...
    url: http://github.com/for-GET

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Europe/Stockholm
future: true
show_drafts: false
markdown: redcarpet
redcarpet:
  extensions:
  - autolink
  - disable_indented_code_blocks
  - fenced_code_blocks
  - no_intra_emphasis
  - strikethrough
  - superscript
  - underline

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:year-:month-:day-:title
relative_permalinks: false

safe: true
lsi: false

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
