title:            Scribble
description:      A jekyll theme. Because I scribble.
url:              # Site url.
baseurl:          /klotter
signoff:          # Your name.
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name: About
    url: /klotter/about.html

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Europe/Stockholm
future: true
show_drafts: false
markdown: redcarpet
redcarpet:
  extensions:
  - autolink
  - disable_indented_code_blocks
  - fenced_code_blocks
  - no_intra_emphasis
  - strikethrough
  - superscript
  - underline

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:year-:month-:day-:title
relative_permalinks: false

safe: true
lsi: false

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
