title:            Scribble
description:      A jekyll theme. Because I scribble.
url:              # Site url.
signoff:          # Your name.
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name: About
    url: /about.html

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Europe/Stockholm
future: true
show_drafts: false
highlighter: pygments
markdown: kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:year-:month-:day-:title
relative_permalinks: false

safe: true
lsi: false

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true
  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap